version: "3.9"
services:
  grafana-oss:
    image: grafana/grafana-oss:11.3.0-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3010:3000
    networks:
      - monitoring_network
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb_container
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - monitoring_network
    volumes:
      - influxdb-volume:/var/lib/influxdb
networks:
  monitoring_network:
    external: true
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
