version: "3.8"
services:
  homepage:
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ./icons:/app/public/icons
networks: {}
